name: example
description: Example project for the simple_speed_dial widget.

publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_speed_dial:
    path: ../

flutter:
  uses-material-design: true
